#! /bin/bash

package=QA-DKRZ

hdf5=hdf5-1.8.14
netcdf=netcdf-4.3.2
zlib=zlib-1.2.8
udunits=udunits-2.2.19

defaultProject=CORDEX

editConfigFile()
{
  # return 0: modified entry, but not disabled
  local args item name

  args=($*)
  args=(${args[*]//=/ })

#  if [ ${#args[*]} -eq 0 ] ; then
#    return 1 # this is a fault
#  el
   if [ ${#args[*]} -eq 1 ] ; then
    name=${args[0]}
  else
    name=${args[0]}
    item=${args[1]}
  fi

  if grep -i -q $name=${item:-enabled} $CONFIG_FILE &> /dev/null; then
    return 0
  fi

  if [ "${item#*=}" = disable -o "${item#*=}" = d ] ; then
    sed -i "/${name}/ d" $CONFIG_FILE &> /dev/null
    test ! -s $CONFIG_FILE && \rm $CONFIG_FILE
    return 1
  elif grep -i -q ${name} $CONFIG_FILE &> /dev/null; then
    sed -i "/${name}/ d" $CONFIG_FILE &> /dev/null
  fi

  echo ${name}=${item:-enabled} >> $CONFIG_FILE
  return 0
}

descript()
{
  echo "Usage: install [options] [project[s]]"
  echo "Purpose: Install/update 'the Quality Control Software Package'"
  echo "for checking climate simulation meta-data provided in netCDF format."
  echo "Details at https://redmine.dkrz.de/projects/cordex/wiki/DKRZ_QC_Tool"
  echo ''
  echo "Options:"
  echo "  -B                Unconditionally re-make all QA executables."
  echo "  -d                Execute 'make' with debugging information."
  echo "  -h                Display usage and exit."
  echo "  --auto-up         Enable automatic updates from the repository at the"
  echo "                    beginning of a run. Suspended by --auto-up=d[isable]."
  echo "  --build           Download and build required libraries."
  echo "  --debug[=script]  Display execution commands. If the name of a script"
  echo "                    called internally is assigned, then debug only this one."
  echo "  --help            Display usage and exit."
  echo "  --link=path       Hard links of external NetCDF installations from the directories"
  echo "                    in 'your-path/${package}/local'."
  echo "                    Shared by all hdf, netcdf, udunits  and zlib."
  echo "  --link_type=path  Same as for 'link' but just for type=netcdf, hdf, zlib, or udunits"
  echo "  --local=str       Path where lib and include directories are to be installed"
  echo "                    [default: QA_DKRZ/local] for both real and hard-links."
  echo "                    Note: unneccesary when install_configure points outside."
  echo "  --show-inst       Display properties of the current installation."
  echo "  --up[date]        Update the QA package from the repository."
  echo "                    Note: not for netCDF, HDF5, udunits2 or zlib."
  echo "  --workspace=str   Path to put updated tables [ ~/.qa-dkrz/tables by"
  echo "                    default]. Also, str is the location of the CF test,"
  echo "                    suite, an example run, and of qc check results for"
  echo "                    omitted option QC_RESULTS. Special: Omitted str "
  echo "                    defaults to the QA-DKRZ path, i.e. as for QC-0.4;"
  echo "                    write permission required. The default for the workspace itself"
  echo "                    is \$HOME\.qa-dkrz [if not available, then the user"
  echo "                    is asked to provide --workspace".
  echo ""
  echo "  project-name      At present CF, CMIP5, and CORDEX; the latter by default."
}

getCurrPaths()
{
  # where all the work is going to take place
  if [ $QA_WORK ] ; then
    test ! -d $QA_WORK && mkdir -p $QA_WORK 2> /dev/null
  else
    if [ $CONDA_ENV ] ; then
      QA_WORK=~/.qa-dkrz
      test ! -d $QA_WORK   && mkdir -p $QA_WORK   2> /dev/null
    else
      QA_WORK=$QA_PATH
    fi
  fi

  # the config filename and location
  if [ ! ${CONFIG_FILE} ] ; then
    if [ -w ~ ] ; then
      local cPath=~/.qa-dkrz
      test ! -d $cPath && mkdir -p $cPath 2> /dev/null

      if [ ${CONDA_ENV} ] ; then
        CONFIG_FILE=$cPath/config.conda
      else
        CONFIG_FILE=$cPath/config.src
      fi

    elif [ -w "$QA_PATH" ] ; then
      test ! -d $QA_PATH/.qa-dkrz && mkdir -p $QA_PATH/.qa-dkrz 2> /dev/null

      if [ ${CONDA_ENV} ] ; then
        CONFIG_FILE=$QA_PATH/.qa-dkrz/config.conda
      else
        CONFIG_FILE=$QA_PATH/.qa-dkrz/config.src
      fi

    elif [ -w "$QA_WORK" ] ; then
      test ! -d $QA_WORK && mkdir -p $QA_WORK/.qa-dkrz 2> /dev/null

      if [ ${CONDA_ENV} ] ; then
        CONFIG_FILE=$QA_WORK/config.conda
      else
        CONFIG_FILE=$QA_WORK/config.src
      fi

    else
      echo "HOME and QA_DKRZ without write permissions,"
      echo "please restart with provided option --workspace=str"
      exit
    fi
  fi

  return
}

getGitBranch()
{
   git branch | grep '*' | awk '{print $2}'
   return
}

getRevNum()
{
  # get current revision number; this determines whether it is
  # before a change of defaults happened.
  local branch currIdent

  if [ $CONDA_ENV ] ; then
    if branch=$(grep branch $QA_PATH/install.log 2> /dev/null) ; then
      branch=${branch#*=}
    fi
    if currIdent=$(grep branch $QA_PATH/install.log 2> /dev/null) ; then
      currIdent=${currIdent#*=}
    fi
  else
    branch=$(getGitBranch)
    currIdent=$(git log --pretty=format:'%h' -n 1)
  fi

  eval ${1}=${branch}-${currIdent}

  return
}

getSrcPath()
{
  # extract the path to the root of the QA package

  # is it in a conda built?
  local x_conda=${0%/qa-dkrz}
  if [ ${x_conda##*/} = bin ] ; then
    x_conda=${x_conda%/bin}
    if [ -d $x_conda/opt/qa-dkrz ] ; then
       CONDA_ENV=t
       export QA_PATH=$x_conda/opt/qa-dkrz
       return
    fi
  fi

  test ${QA_PATH} && return

  local target isInvalid

  if [ ${1:0:1} = '/' ] ; then
    target=$1
  else
    target=$(pwd)/$1
  fi

  if [ -h $target ] ; then

    # get the link
    local link=$(ls -l $target | awk  '{print $(NF)}')

    # link is relative, so make it absolute
    test ${link:0:1} != '/' && link=${target%/*}/${link}

    getSrcPath ${link}

  elif [ -f $target ] ; then

    # a real instance, at first resolve .. and .
    # works also for . or .. in the middle of the path

    local xname=${target##*/}
    target=${target%/*}  # remove the name of the script

    local arr=( ${target//\// } )

    local i j sz
    sz=${#arr[*]}

    for(( i=1 ; i < sz ; ++i )) ; do

      if [ "${arr[i]}" = '.' ] ; then
        unset arr[i]
      elif [ "${arr[i]}" = '..' ] ; then
        j=$((i-1))

        # this takes into account adjacent . and/or .. with any depth
        while [ ! ${arr[j]} ] ; do
          j=$((j-1))
        done
        unset arr[j]
        unset arr[i]
      fi
    done

    # get rid of empty items
    arr=( ${arr[*]} )

    sz=${#arr[*]}

    local tmp
    for(( i=0 ; i < sz ; ++i )) ; do
      tmp=${tmp}/${arr[i]}

      if [ -f ${tmp}/.install_configure ] ; then
        export QA_PATH=$tmp
        break
      fi
    done

    test $i -eq $sz && isInvalid=t
  else
    isInvalid=t
  fi

  if [ ${isInvalid:-f} = t ] ; then

    local str=$(ls -l $target 2> /dev/null | awk  '{print $(NF)}')

    if [ ${#str} -gt 0 ] ; then
      str="invalid path=$0"
    else
      str="broken path=$0"
    fi

    echo "${str}"

    exit 1
  fi

  export QA_PATH=${QA_PATH}

  return
}

log()
{
  if [ ${isContinueLog:-f} = f ] ; then
    isContinueLog=t

    local logTxt="\n$(date +'%F_%T'):"
    echo -e "${logTxt} install $*" >> install.log
  fi

  return
}

saveAsCycle()
{
  for f in $* ; do
    if [ ! \( -f $f -o -d $f \) ] ; then
      echo "install.saveAsCycle: no such file or directory $f"
      return
    fi

    local ext val x
    local maxVal fs fx

    maxVal=0
    fs=( $(ls -d $f.* 2> /dev/null) )

    for fx in ${fs[*]} ; do
      ext=${fx##*.}

      if val=$(expr match $ext '\([[:digit:]]\+$\)' 2> /dev/null) ; then
        test ${val:-0} -gt ${maxVal} && maxVal=$val
      fi
    done

    mv $f ${f}.$((++maxVal)) 2> /dev/null
  done
}

tr_option()
{
  local phrase="${!1}"

  local sz i
  local sz=${#phrase}
  for((i=0 ; i < sz ; ++i )) ; do
    test "${phrase:i:1}" = '=' && break
  done

  if [ ${i} -eq ${sz} ] ; then
    phrase=$( echo "${phrase/% /}" | tr "[:lower:]" "[:upper:]" )
    phrase=$( echo "${phrase}" | tr "-" "_" )
  else
    local tmp0="${phrase:0:i}"
    tmp0="${tmp0//QC/QA}"
    tmp0=$( echo "${tmp0/% /}" | tr "[:lower:]" "[:upper:]" )
    tmp0=$( echo "${tmp0}" | tr "-" "_" )
    phrase="${tmp0}""${phrase:i}"
  fi

  eval ${1}=\${phrase}
  return
}

update()
{
  if [ ${isAutoUp} ] || \
  editConfigFile AUTO_UPDATE=$AUTO_UPDATE ; then
    if [ $CONDA_ENV ] ; then
      # look for a new conda-built package
      local tmp
      declare -a tmp
      tmp=( $(conda search -c birdhouse qa-dkrz 2> /dev/null) )

      local i item
      for(( i=0 ; i < ${#tmp[*]} ; ++i )) ; do
        if [ ${tmp[i]} = '*' ] ; then
          item=${tmp[++i]}
          item=${item}-${tmp[++i]}

          if ! editConfigFile CONDA_BUILD=$item ; then
            conda update -c birdhouse qa-dkrz &> /dev/null

            getRevNum packRev
            editConfigFile QA_REVISION=$packRev

            exitVal=101
          fi
          break
        fi
      done

    elif [ ! -f ${QA_PATH}/.ignore_GitHub_update ] ; then
      cd $QA_PATH

      # is qa-dkrz going to change?
      local qa_dkrzDate=$(ls -l \
           --time-style=+'%s' ${QA_PATH}/scripts/qa_dkrz \
           | awk '{print $6}' 2> /dev/null )

      test "$(getGitBranch)" != master && \
        git checkout master &> /dev/null

      git pull --no-edit -q origin master &> /dev/null

      if [ ${qa_dkrzDate} != $( ls -l \
           --time-style=+'%s' ${QA_PATH}/scripts/qa_dkrz \
           | awk '{print $6}' 2> /dev/null ) ] ; then
        exitVal=101
      fi

      # revison num of the updated package
      getRevNum packRev

      editConfigFile QA_REVISION=$packRev
    fi
  fi

  if editConfigFile AUTO_TABLE_UPDATE=$AUTO_TABLE_UPDATE \
      || ${FORCE_RSYNC:-f} = t ; then
    if [ "$QA_WORK" != "$QA_PATH" ] ; then
      rsync -auz $QA_PATH/tables $QA_WORK &> /dev/null
    fi

    ${QA_PATH}/scripts/get_cfconventions \
        --config_file=$CONFIG_FILE \
        ${QA_WORK}/tables/projects/CF
  fi

  return
}


# ----- main ------

zeroArg=$0
allArgs=($*)

if [ $# -gt 0 ] ; then
  # save arguments
  sArgs=($*)

  # higher priority options
  for(( i=0 ; i < ${#sArgs[*]} ; ++i )) ; do
    # some args are accepted without '--'
    A="${sArgs[i]}"
    tr_option A

    if [ "${A:0:5}" = AUTO_ ] ; then
      sArgs[${i}]=--${sArgs[${i}]}
      A="--${A}"
    elif [ "${A:0:5}" = DEBUG ] ; then
      sArgs[${i}]=--${sArgs[${i}]}
      A="--${A}"
    elif [ "${A:0:4}" = HELP ] ; then
      sArgs[${i}]=--${sArgs[${i}]}
      A="--${A}"
    elif [ "${A:0:4}" = LINK ] ; then
      sArgs[${i}]=--${sArgs[${i}]}
      A="--${A}"
    elif [ "${A:0:6}" = ONLY-Q ] ; then
      sArgs[${i}]=--${sArgs[${i}]}
      A="--${A}"
    elif [ "${A:0:3}" = SRC  ] ; then
      sArgs[${i}]=--${sArgs[${i}]}
      A="--${A}"
    elif [ "${A:0:2}" = UP ] ; then
      sArgs[${i}]=--${sArgs[${i}]}
      A="--${A}"
    fi

    if [ "${A%=*}" = '--DEBUG' ] ; then
      test ${A} = '--DEBUG' -o ${A#*=} = ${0##*/} && set -x
    fi
  done
fi

while getopts Bdh-: option ${sArgs[*]}
do
  UOPTARG="${OPTARG}"
  tr_option UOPTARG

  case $option in
    B)  coll[${#coll[*]}]=-B ;;
    d)  coll[${#coll[*]}]=-d ;;
    h)  descript
        exit ;;
    -)  if [ "${UOPTARG:0:7}" = AUTO_UP ] ; then
          AUTO_UP=${OPTARG##*=}
          isAutoUp=t
        elif [ "${UOPTARG:0:13}" = AUTO_TABLE_UP ] ; then
          AUTO_TABLE_UPDATE=${OPTARG##*=}
          isAutoTableUp=t
        elif [ "${UOPTARG:0:5}" = BUILD ] ; then
          isBuild=t
        elif [ "${UOPTARG:0:11}" = CONFIG_FILE ] ; then
          CONFIG_FILE=${OPTARG##*=}
        elif [ ${UOPTARG:0:5} = DEBUG -o ${UOPTARG} = 'DEBUG=install' ] ; then
          set -x
        elif [ "${UOPTARG%%=*}" = HELP ] ; then
          descript
          exit
        elif [ "${UOPTARG:0:4}" = LINK ] ; then
          isLink=t
        elif [ "${UOPTARG:0:6}" = ONLY_Q ] ; then
          :  # for backward compatibilty
        elif [ "${UOPTARG:0:7}" = QA_PATH ] ; then
          export QA_PATH=${OPTARG##*=}
        elif [ "${UOPTARG:0:7}" = QA_WORK ] ; then
          QA_WORK=${OPTARG##*=}
        elif [ "${UOPTARG}" = SRC ] ; then
          :  # for backward compatibilty
        elif [ "${UOPTARG:0:2}" = UP ] ; then
          isUpdateQA=t
        elif [ "${UOPTARG:0:9}" = WORKSPACE ] ; then
          QA_WORK=${UOPTARG##*=}
        fi

        # collect options, which have not been processed above
        coll[${#coll[*]}]=--${OPTARG}
        ;;
   \?)  descript
        echo $*
        exit 1 ;;
  esac
done

shift $(( $OPTIND - 1 ))

for pck in $* ; do
  PCK="${pck}"
  tr_option PCK

  if [ ${PCK:0:4} = ZLIB ] ; then
    zlib=${pck}
  elif [ ${PCK:0:4} = HDF5 ] ; then
    hdf5=${pck}
  elif [ ${PCK:0:6} = NETCDF ] ; then
    netcdf=${pck}
  elif [ ${PCK:0:7} = UDUNITS ] ; then
    udunits=${pck}
  elif [ ${PCK:0:7} = QA_WORK ] ; then
    QA_WORK=${PCK:8}
    FORCE_RSYNC=t
  else
    coll[${#coll[*]}]=$pck  # collect project names
  fi
done

getSrcPath $zeroArg  # sets also CONDA_ENV
getCurrPaths
update

test ${CONDA_ENV} && exit  # miniconda built executables

pcks="--zlib=$zlib --hdf5=$hdf5 --netcdf=$netcdf --udunits=$udunits"

if [ ${isBuild:-f} = t -a ${isLink:-f} = t ] ; then
  echo "scripts/install.sh: options --build and --link exclude each other"
  exit 1
elif [ ${isBuild:-f} = t -o ${isLink:-f} = t ] ; then
  log ${allArgs[*]}
else
  pcks=
fi

exec $QA_PATH/scripts/install.sh ${debug} --pack=${package} \
${isContinueLog:+--continue_log} ${pcks} \
${coll[*]}
