#! /bin/bash

descript()
{
  echo -e "\nUsage: cf-checker [opts] netCDF-file[s]"
  echo "Purpose: Check for CF Conventions Compliance."
  echo "The checker is part of the QA-DKRZ package and must have been compiled"
  echo "by '/your-path-to-QA-DKRZ/install CF'."
  echo " -C str  CF Convention string; taken from global attributes by default."
  echo " -F path Find all nc-files in sub-dirs of path."
  echo " -p str  Path to one or more netCDF Files; this is prefixed"
  echo "         only to files without any path component."
  echo " -R      Apply also CF recommendations."
  echo " -x str  Path to QA-DKRZ/bin; required if this script"
  echo "         is located outside QA-DKRZ/scripts."
  echo " --debug"
  echo " --help"
  echo " --param-file-only"
  echo " --with-comments"
  echo " netCDF-file(s)"

  exit
}

getPath()
{
  # Note: each executable invoked on a bash command-line
  # gets its name in parameter $0, which is available
  # in functions.

  if [ ${#qPath} -eq 0 ] ; then
    # init
    if [ ${0:0:1} = '/' ] ; then
      qPath=${0%/*}
    else
      qPath=$(pwd)/${0%/*}
    fi

    xName=${0##*/}
  fi

  if [ -h $qPath/$xName ] ; then

    qPath=$(ls -l $qPath/${xName} | awk  '{print $(NF)}')
    xName=${qPath##*/}
    qPath=${qPath%/*}

    getPath

  else

    # resolve .. and .
    local arr=( ${qPath//\// } )

    # any //, ., or .. in the middle of the path?
    local i j sz
    sz=${#arr[*]}

    for(( i=1 ; i < sz ; ++i )) ; do
      j=$((i-1))

      if [ "${arr[i]}" = '/' -a "${arr[j]}" = '/' ] ; then
        unset arr[j]
      elif [ "${arr[i]}" = '.' ] ; then
        unset arr[i]
      elif [ "${arr[i]}" = '..' ] ; then
        while [ ${#arr[j]} -eq 0 ] ; do
          j=$((j-1))
        done
        unset arr[j]
        unset arr[i]
      fi
    done

    # get rid of empty items
    arr=( ${arr[*]} )

    sz=${#arr[*]}
    qPath=

    for(( i=0 ; i < sz ; ++i )) ; do
      qPath=${qPath}/${arr[i]}
    done

  fi

  local tmp
  while [ "${qPath}" != "${qPath%/*}" ] ; do
    tmp=${qPath##*/}
    test ${tmp:0:3} = 'QA-' && return

    qPath=${qPath%/*}
  done

  descript

  if [ ${#xPath} -gt 0 ] ; then
    echo -e "\nPlease, check option -x; found ${xPath}."
  else
    local str
    str="\nThis script was executed from out-side of the QA package."
    str="${str}\nIt was probably copied or hard-linked. Please, use a"
    str="${str}\nsymbolic link, or call it directly from /path/QA-DKRZ/scripts,"
    str="${str}\nor use option -x."

    echo -e "${str}"
  fi

  exit
}

# -------  main -----
test $# -eq 0 && descript

# get execution path of QA scripts

while getopts C:F:hp:Rx:-: option ${args[*]}
do
  case $option in
    C)  CF=${OPTARG}
#        test ${CF:0:2} = CF && CF=${CF:2}
#        test ${CF:0:1} = '-' && CF=${CF:1}
        ;;
    F)  findPath=$OPTARG ;;
    h)  descript ;;
    p)  fPath=${OPTARG} ;;
    R)  RC=t ;;
    x)  xPath=${OPTARG}
        qPath=$xPath
        ;;
    -)  if [ "$OPTARG" = "help" ] ; then
          descript
        elif [ "${OPTARG}" = "debug" ] ; then
          set -x
        elif [ "${OPTARG:0:5}" = "param" ] ; then
          isParamFileOnly=t
        elif [ "${OPTARG}" = "test-suite" ] ; then
          isTestSuite=t
        elif [ "${OPTARG}" = "ts" ] ; then
          isTestSuite=t
        fi
        ;;
   \?)  descript
  esac
done

shift $(( $OPTIND - 1 ))

getPath

cd $qPath
./install CF &> /dev/null
cd - &> /dev/null

# files
if [ ${isTestSuite:-f} = t ] ; then
  # only these fomr the set of test files
  ts_fs=( $* )
else
  fs=( $* )
fi

if [ ${#findPath} -gt 0 ] ; then
  fs=( ${fs[*]} $( find ${findPath} -name "*.cn" ) )
  fs=( ${fs[*]} $( find ${findPath} -name "*.nc" | sort ) )
fi

param_T="\\n-t ${qPath}/tables/projects/CF"

param_IN="\\nIN::oCF"

param_CF="\\nCF::cFSN=cf-standard-name-table.xml"
param_CF="${param_CF}:cFAT=CF_area-type-table.txt"
param_CF="${param_CF}:cFSRN=CF_standardized-region-names.txt"
param_CF="${param_CF}${CF:+:cF=}${CF}${RC:+:fR}"

param_X="${param_X}\\nX::cL=CF_check-list.conf:nCR:nLL=L1:oP:d"
#param_X="${param_X}:note={CF_12h,D}"  # data variable without any data


if [ ${isParamFileOnly:-f} = f ] ; then
  echo -e "\n========================================"
  echo -e "\nDKRZ-CF-Checker run ($(date +'%F %T')):"
fi

for(( i=0 ; i < ${#fs[*]} ; ++i )) ; do

  # only selected ones from the set of test files
  if [ ${#ts_fs[*]} -gt 0 ] ; then
    for(( i_ts=0 ; i_ts < ${#ts_fs[*]} ; ++i_ts )) ; do
      test ${fs[i]##*/} = ${ts_fs[i_ts]} && break
    done
    test ${i_ts} -eq ${#ts_fs[*]} && continue
  fi

  param=

  # prepare parameters for the cf-checker.x
  test ${#fPath} -gt 0 && param="-p ${fPath}\\n"

  param="${param}-f ${fs[i]}"
  param="${param}${param_T}"
  param="${param}${param_IN}"
  param="${param}${param_CF}"

  param="${param}${param_X}:note="
  if [ ${isTestSuite:-f} = t ] ; then
    if [ ${fs[i]##*/} != cf_0f.nc ] ; then
      param="${param},{CF_0d,D},{CF_0e,D},{CF_0f,D},{CF_12e,D}"
    fi
  fi

  if [ ${isParamFileOnly:-f} = t ] ; then
    echo -e "$param" > param_file.txt
    exit
  fi

  param="$(echo -e $param)"
  $qPath/bin/cf-checker.x ${param}

  if [ ${isTestSuite:-f} = t ] && echo ${fs[i]} | grep -q Fail ; then
    asdf="$(ncdump -h ${fs[i]} | grep :comment[^[:digit:]])"
    echo -e "${asdf#*:}\n"
  fi
done

echo "========================================"

test -e param_file_$$.txt && \rm param_file_$$.txt
