#! /bin/bash

descript()
{
  echo -e "\ninstall_local_netcdf"
  echo "  -q               Quiet."
  echo "  --debug[=script] Display execution commands."
  echo "  --help           Also option -h."
  echo "  --prefix=path    Path to the installation dir."
}

c()
{
#  export CC="/usr/bin/gcc"
   export CFLAGS="${CFLAGS} -I $prefix/include "
   export CPPFLAGS="${CPPFLAGS} -I $prefix/include "
#  export CXX=""
#  export CXXFLAGS=""
#  export FC=""
#  export F90=""
   export LDFLAGS="-L$prefix/lib -L$prefix/lib64"
   export LD_LIBRARY_PATH=$prefix/lib:$prefix/lib64

  #--enable-cxx-4
  #--enable-docs-install
  ./configure --prefix=${prefix} \
    --enable-netcdf-4  --disable-dap &> ${out}

  #--disable-fortran-compiler-check --disable-f77

  return $?
}

tr_option()
{
  local phrase="${!1}"

  local sz i
  local sz=${#phrase}
  for((i=0 ; i < sz ; ++i )) ; do
    test "${phrase:i:1}" = '=' && break
  done

  if [ ${i} -eq ${sz} ] ; then
    phrase=$( echo "${phrase/% /}" | tr "[:lower:]" "[:upper:]" )
  else
    local tmp0="${phrase:0:i}"
    tmp0="${tmp0//QC/QA}"
    tmp0=$( echo "${tmp0/% /}" | tr "[:lower:]" "[:upper:]" )
    phrase="${tmp0}""${phrase:i}"
  fi

  eval ${1}=\${phrase}
  return
}

# main

# QA_PATH was exported
mkdir -p $QA_PATH/local/source
out=$QA_PATH/local/source/INSTALL_netcdf.log

while getopts hp:q-: option ${args[*]}
do
  UOPTARG="$OPTARG"
  tr_option UOPTARG

  case $option in
    h)  descript
        exit ;;
    q)  QUIET=t ;;
    -)  if [ "${UOPTARG%%=*}" = PREFIX ] ; then
           prefix=${OPTARG#*=}
        elif [ "$UOPTARG" = HELP ] ; then
           descript
           exit
        elif [ "${UOPTARG%=*}" = DEBUG ] ; then
           test "${UOPTARG}" = DEBUG -o ${OPTARG#*=} = ${0##*/} && set -x
        elif [ "$UOPTARG" = DISTCLEAN ] ; then
           isDistClean=t
        fi
        ;;
   \?)  descript
        exit 1 ;;
  esac
done

shift $(( $OPTIND - 1 ))

src=$installPath/source

if [ -d "$src" ] ; then
  cd $src &> /dev/null
else
  exit 1
  return
fi

if [ ${isDistClean:-f} = t ] ; then
  make distclean  >>${out} 2>&1
  echo -e "\n-------------\n"  >>${out} 2>&1
  exit 0
fi

# configure and make for C

if ! c ; then
  status=$?
  echo "${src##*/}: configure failed"
  exit $status
fi

if ! make check install  >>${out} 2>&1 ; then
  status=$?
  echo "${src##*/}: make check install failed"
  exit $status
fi

exit 0
