#! /bin/bash

descript()
{
  echo -e "\ninstall_local_hdf5"
  echo "  -q             Quiet."
  echo "  --debug[=script]  Display execution commands."
  echo "  --help         Also option -h."
  echo "  --prefix=path  Path to the installation dir."
}

tr_option()
{
  local phrase="${!1}"

  local sz i
  local sz=${#phrase}
  for((i=0 ; i < sz ; ++i )) ; do
    test "${phrase:i:1}" = '=' && break
  done

  if [ ${i} -eq ${sz} ] ; then
    phrase=$( echo "${phrase/% /}" | tr "[:lower:]" "[:upper:]" )
  else
    local tmp0="${phrase:0:i}"
    tmp0="${tmp0//QC/QA}"
    tmp0=$( echo "${tmp0/% /}" | tr "[:lower:]" "[:upper:]" )
    phrase="${tmp0}""${phrase:i}"
  fi

  eval ${1}=\${phrase}
  return
}

# ------ main -------

# QA_PATH was exported
mkdir -p $QA_PATH/local/source
out=$QA_PATH/local/source/INSTALL_hdf.log

while getopts hp:q-: option ${args[*]}
do
  UOPTARG="$OPTARG"
  tr_option UOPTARG

  case $option in
    h)  descript
        exit ;;
    q)  QUIET=t ;;
    -)  if [ "${UOPTARG%=*}" = DEBUG ] ; then
           test "${UOPTARG}" = DEBUG -o ${OPTARG#*=} = ${0##*/} && set -x
        elif [ "$UOPTARG" = DISTCLEAN ] ; then
           isDistClean=t
        elif [ "$UOPTARG" = HELP ] ; then
           descript
           exit
        elif [ "${UOPTARG%%=*}" = PREFIX ] ; then
           installPath=${OPTARG#*=}
           prefix=--${OPTARG}
        fi
        ;;
   \?)  descript
        exit 1 ;;
  esac
done

shift $(( $OPTIND - 1 ))

src=$installPath/source

if [ -d "${src}" ] ; then
  cd $src &> /dev/null
else
  exit 1
  return
fi

if [ ${isDistClean:-f} = t ] ; then
  make distclean  >>${out} 2>&1
  echo -e "\n-------------\n"  >>${out} 2>&1
  exit 0
fi

#export CC=/usr/bin/gcc
#export CFLAGS='-static -O2'
#export CPPFLAGS=
#export CXX=/usr/bin/g++
#export CXXFLAGS='-static -O2'

./configure ${prefix} --enable-cxx --enable-hl \
  --disable-fortran --disable-parallel \
  --with-zlib=$installPath  >>${out} 2>&1

test $? -gt 0 && exit 1

if ! make  >>${out} 2>&1 ; then
  echo "${src##*/}: make failed" 1>&2
  exit 2
fi

if ! make check  >>${out} 2>&1 ; then
  echo "${src##*/}: make check failed" 1>&2
  exit 3
fi           # run test suite.

if ! make install  >>${out} 2>&1 ; then
  echo "${src##*/}: make install failed"  1>&2
  exit 4
fi

if ! make check-install  >>${out} 2>&1  ; then
  echo "${src##*/}: make check-install failed" 1>&2
  exit 5
fi  # verify installation


exit 0
