#! /bin/bash

descript()
{
  echo -e "\ninstall_local_zlib"
  echo "  -q                Quiet."
  echo "  --debug[=script]  Display execution commands."
  echo "  --distclean       Display execution commands."
  echo "  --help            Also option -h."
  echo "  --prefix=path     Path to the installation dir."
  echo "  --src_name=string Package name."
}

# ------ main -------

QC_SRC=${0%/*}
test ${QC_SRC##*/} = scripts && QC_SRC=${QC_SRC%/*}

mkdir -p $QC_SRC/local/source
out=$QC_SRC/local/source/INSTALL_zlib.log

while getopts hq-: option $* #{args[*]}
do
  case $option in
    h)  descript
        exit ;;
    q)  QUIET=t ;;
    -)  if [ "${OPTARG%=*}" = "debug" ] ; then
           test ${OPTARG} = debug -o ${OPTARG#*=} = ${0##*/} && set -x
        elif [ "$OPTARG" = "distclean" ] ; then
           isDistClean=t
        elif [ "$OPTARG" = "help" ] ; then
           descript
           exit
        elif [ "${OPTARG%%=*}" = "prefix" ] ; then
           prefix=--${OPTARG}
        elif [ "${OPTARG%%=*}" = "src" ] ; then
           src=${OPTARG#*=}
        fi
        ;;
   \?)  descript
        exit 1 ;;
  esac
done

shift $(( $OPTIND - 1 ))

if [ -d "$src" ] ; then
  cd $src &> /dev/null
else
  exit 1
  return
fi

if [ ${isDistClean:-f} = t ] ; then
  make distclean  >>${out} 2>&1
  echo -e "\n-------------\n"  >>${out} 2>&1
  exit 0
fi

#export CC="/usr/bin/gcc"
#export CFLAGS="-static -O2"
unset LD_LIBRARY_PATH

if ! ./configure ${prefix}  >>${out} 2>&1 ; then
  exit $?
fi

if ! make test  >>${out} 2>&1 ; then
  exit $?
fi

if ! make install  >>${out} 2>&1 ; then
  exit $?
fi

exit 0
