#! /bin/bash

package=QA-DKRZ  # default

check_targets()
{
  # $1: variable name for a return value
  local kind=$1
  local target=$2

  if [ ! -d ${target} ] ; then
    log "${target}: no such directory" FAIL
    return 1
  fi

  if [ ${kind} = zlib ] ; then

    if ls ${target}/lib/libz.* &> /dev/null ; then
      lib=lib
    else
      if ls ${target}/lib64/libz.* &> /dev/null ; then
        lib=lib64
      else
        return 1
      fi
    fi

    if ! ls ${target}/include/zlib.h &> /dev/null ; then
      return 1
    fi

  elif [ ${kind} = hdf5 ] ; then

    if  ls ${target}/lib/libhdf5* &> /dev/null ; then
      lib=lib
    else
      if  ls ${target}/lib64/libhdf5* &> /dev/null ; then
        lib=lib64
      else
        return 1
      fi
    fi

    if ! ls ${target}/include/hdf5.h &> /dev/null ; then
      return 1
    fi

  elif [ ${kind} = netcdf ] ; then

    if ls ${target}/lib/libnetcdf* &> /dev/null ; then
        lib=lib
    else
      if ls ${target}/lib64/libnetcdf* &> /dev/null ; then
        lib=lib64
      else
        return 1
      fi
    fi

    if ! ls ${target}/include/netcdf.h &> /dev/null ; then
      return 1
    fi

  elif [ ${kind} = udunits ] ; then

    if ls ${target}/lib/libudunits2* &> /dev/null ; then
      lib=lib
    else
      if ls ${target}/lib64/libudunits2* &> /dev/null ; then
        lib=lib64
      else
        return 1
      fi
    fi

    if ! ls ${target}/include/udunits2.h &> /dev/null ; then
      return 1
    fi

  fi

  mkdir -p local/$lib

  return 0
}

cmpStrings()
{
  # if comparison is true, then return 0; else 0

  if [ $# -ne 3 ] ; then
    echo 'cmpStrings() requires: string1 operator string2.'
    exit 1
  fi

  local s0=$1
  local op=$2
  local s1=$3

  local res
  res=( $(echo -e "${s0}\n${s1}" | sort ) )

  # equal?
  if [ ${res[0]} = ${res[1]} ] ; then
    if [ ${op} = '-eq' -o ${op:2:1} = 'e' ]  ; then
      return 0
    else
      return 1
    fi
  else
    # strings are not equal, but this was asked
    test ${op} = '-eq' && return 1
  fi

  # convert e.g. -le to -lt
  if [ ${op:2:1} = 'e' ]  ; then
    op=${op:0:2}t
  fi

  local ret=1

  if [ ${op} = '-lt' ] ; then
    test ${res[0]} = $s0 && ret=0
  elif [ ${op} = '-gt' ] ; then
    test ${res[0]} = $s1 && ret=0
  fi

  return $ret
}

descript()
{
  echo -e "\ninstall_local [opts]"
  echo "Usage: Provide access and/or installation of libraries"
  echo "versions zlib-1.2.7, hdf5-1.8.10, and netcdf-4.2.1.1 of higher;"
  echo "by default from ftp://ftp-unidata.ucar.edu/pub/netcdf/... ."
  echo "Static libs will be installed by default in"
  echo "your-path/$package/local. Alternatively, links may be established"
  echo "to external installations or installations may be accomplished"
  echo "in external sources (requires write permission for externals)."
  echo "Priority for compiler settings:"
  echo "    1) those in file $package/install_configure, if existing"
  echo "    2) given in environmental variables CC, CXX, etc."
  echo "    3) find gcc and g++ executables."
  echo "    4) file 'install_configure' ready for special editing; EXIT"
  echo "Options:"
  echo "  --continue_log Iternal processing option."
  echo "  --debug[=script]  Display execution commands."
  echo "  --distclean"
  echo "  --help         Also option -h."
  echo "  --link=str     Hard-link of external NetCDF installation to the directories"
  echo "                 in 'your-path/$package/local'."
  echo "  -q             Quiet for successful operation."
  echo "  --src-path=path To the place were all three packages reside."
}

distclean()
{
  for f in bin include lib lib64 share ; do
    \rm -rf ${QA_PATH}/local/$f
  done
  \rm -f ${QA_PATH}/local/source/INDSTALL_*.log

  local name

  for t in zlib hdf5 netcdf udunits ; do
    eval name=\${curr_${t}}

    bash ${QA_PATH}/scripts/install_local_${t} --distclean  \
       -q --prefix=${qaLocalPath} ${QUIET:+-q}
  done

  return
}

editInstallConfigure_build()
{
  # adjust eventually install_configure settings
  # of LIB and INCLUDE to new paths

  local ic=install_configure

  if grep -q "^LIB=" ${QA_PATH}/$ic 2> /dev/null ; then
    sed -i "/^LIB=/ c ${lib}" install_configure
  else
    # append after line '# e.g. LIB=...'
    sed -i "/LIB=/ a LIB=${lib}" install_configure
  fi

  if grep -q "^INCLUDE=" ${QA_PATH}/$ic 2> /dev/null ; then
    sed -i "/^INCLUDE=/ c ${incl}" install_configure
  else
    sed -i "/INCLUDE=/ a INCLUDE=${incl}" install_configure
  fi

  return
}

editInstallConfigure_link()
{
  local numOfLinks=$1

  # adjust eventually install_configure settings
  # of LIB and INCLUDE to new paths

  # procedure for LIB is more intricate, because of lib and lib64

  # linked libs are collected, but multiple names are possible.
  local libs
  declare -a libs

  # map lib and lib64 always to QA_DKRZ/local

  libs=( lib lib64 )
  incls=( include )

  local nI nL oI oL px
  declare -a nI nL oI oL

  local px i1 j

  local ic=install_configure

  # should not happen
  test ! -f ${QA_PATH}/$ic && \
     cp ${QA_PATH}/.$ic ${QA_PATH}/ic

  # avoid duplicates
  # get items from ic and test for a valid path
  local isLIB isINCLUDE

  # if there was not a change for all h, n ,u, z
  if [ $numOfLinks -lt 4  ] ; then
    if px=$(grep "^LIB=" ${QA_PATH}/$ic 2> /dev/null ) ; then
      isLIB=t
    fi
    px=${px#LIB=}
    oL=(${px//:/ })
    for(( i1=0 ; i1 < ${#oL[*]} ; ++i1 )) ; do
      if [ ! -d ${oL[i1]} ] ; then
        oL[${i1}]=
      fi
    done

    if px=$(grep "^INCLUDE=" ${QA_PATH}/$ic 2> /dev/null ) ; then
      isINCLUDE=t
    fi
    px=${px#INCLUDE=}
    oI=(${px//:/ })
    for(( i1=0 ; i1 < ${#oI[*]} ; ++i1 )) ; do
      if [ ! -d ${oI[i1]} ] ; then
        oI[${i1}]=
      fi
    done
  fi

  nL=( ${libs[*]/#/${QA_PATH}\/local\/} ${oL[*]} )
  nI=( ${incls[*]/#/${QA_PATH}\/local\/} ${oI[*]} )

  local lib
  for i1 in ${nL[*]} ; do
    lib=${lib}${lib:+:}$i1
  done
  lib='LIB='${lib}

  local incl
  for i1 in ${nI[*]} ; do
    incl=${incl}${incl:+:}$i1
  done
  incl='INCLUDE='${incl}

  # adjustment
  if [ ${isLIB:-f} = t ] ; then
    sed -i "/^LIB=/ c ${lib}" install_configure
  else
    # append after line '# e.g. LIB=...'
    sed -i "/LIB=/ a LIB=${lib}" install_configure
  fi

  if [ ${isINCLUDE:-f} = t ] ; then
    sed -i "/^INCLUDE=/ c ${incl}" install_configure
  else
    sed -i "/INCLUDE=/ a INCLUDE=${incl}" install_configure
  fi

  return
}

f_build()
{
  local c dir is

  if ls ${qaLocalPath}/lib/lib${1}.* &> /dev/null \
        || ls ${qaLocalPath}/lib64/lib${1}.* &> /dev/null ; then
      log ${1} DONE=up-to-date
      return 0  # go on
  fi

  cd ${qaLocalPath}/source

  # rebuild

  # instance already available?
  dir=$( ls -d ${qaLocalPath}/source/curr_${1}* 2> /dev/null )
#  test ${#dir} -gt 0 && \rm -rf $dir

  local name
  eval name=\${curr_${1}}

  if [ ${#dir} -eq 0 ] ; then

    local text
    if [ ${name:0:1} = 'n' ] ; then
      text="-l1 -np -nc ftp://ftp.unidata.ucar.edu/pub/netcdf/old/${name}.tar.gz"
      wget ${text} &> INSTALL_netcdf.log
    elif [ ${name:0:1} = 'h' ] ; then
      text="-l1 -np -nc www.hdfgroup.org/ftp/HDF5/releases/${name}/src/${name}.tar.gz"
      wget ${text} &> INSTALL_hdf.log
    elif [ ${name:0:1} = 'z' ] ; then
      text="-l1 -np -nc www.zlib.net/${name}.tar.gz"
      wget ${text} &> INSTALL_zlib.log
    elif [ ${name:0:1} = 'u' ] ; then
      text="-O - ftp://ftp.unidata.ucar.edu/pub/udunits/${name}.tar.gz"
      wget ${text}
    fi

    if [ $? -eq 0 ] ; then
      log "download: $name" DONE
    else
      log "wget ${text}:" FAIL
      exit 1
    fi

    if [ -f $name.tar.gz ] ; then
      gzip -d $name.tar.gz 2> /dev/null
      tar xf $name.tar > /dev/null
      \rm -f $name.tar
    fi
  fi

  bash ${QA_PATH}/scripts/install_local_${1}  \
     ${isDebug:+--debug} ${QUIET:+-q} \
     --prefix=${qaLocalPath} \

  local status=$?

  if [ ${status} -gt 0 ] ; then
    myStat=FAIL
  else
    myStat=DONE
  fi

  log ${QA_PATH}/scripts/install_local_${1} ${isDebug:+--debug} \
  --prefix=${qaLocalPath} ${QUIET:+-q} ${myStat}

  test ${myStat} = FAIL && exit 1

  cd - &> /dev/null

  editInstallConfigure_build

  return $status
}

f_link()
{
  local ret=0
  local i is
  local changeCount=0

  local names=( hdf5 netcdf udunits zlib )
  local ids=( h n u z )

  local lib  # value is returned by ln_'name'()

  for((i=0 ; i < ${#ids[*]} ; ++i )) ; do

    local lnk llnk
    eval lnk=\$link_${ids[i]}
    lnk=${lnk%/lib*}  # if appended
    test ${#lnk} -eq 0 && continue

    # request: only hard links
    if [ ${#lnk} -gt 0 ] ; then
      is=f

      if ln_${names[i]} ${lnk} ; then
        is=t
        changeCount=$(( changeCount +1 ))
      fi

      if [ ${is} = t ] ; then
        log "${names[i]}: ${lnk}/${lib} hard-linked in ${QA_PATH}/local" DONE
      else
        log "linking of ${names[i]} to ${lnk}" FAIL
        ret=1
      fi
    fi

  done

  test ${ret} -eq 1 && return 1

  editInstallConfigure_link $changeCount

  return 0
}

findPackage()
{
  local packs
  declare -a dirs

  packs=( $( ls -d ${1}/${2}-* | sort ) )
  eval curr_${2}=${packs[0]##*/}

  test ${#packs[*]} -eq 0 && return 0

  return 1
}

formatText()
{
  # format text ready for printing

  # date and host
  local k N n str0 str isWrap

  str0="$*"

  # The total output is subdivided into chunks of pmax characters.
  # Effect of \n is preserved.
  N=$pEnd  # special: taken from log()
  str=

  while : ; do
    k=0  # necessary when skipping the loop

    if [ ${isWrap:-f} = t ] ; then
      n=$(( N - 6 ))
    else
      n=$N
    fi

    if [ ${#str0} -ge $n ] ; then
      # wrap lines with length > N
      for (( ; k < n ; ++k )) ; do
        if [ "${str0:k:2}" = "\n" ] ; then
          str="${str}${str0:0:k}\n"
          str0=${str0:$((k+2))}
          isWrap=f
          continue 2
        fi
      done
    fi

    # the last line
    if [ ${#str0} -le $n ] ; then
      str="${str}${str0}"
      break

    # sub-lines length equals N
    elif [ $k -eq $n -a "${str0:k:2}" = "\n" ] ; then
      str="${str}${str0:0:n}"
      str0=${str0:n}

    # wrap line
    else
      str="${str}${str0:0:n}\n      "
      str0=${str0:n}
      isWrap=t
    fi
  done

  if [ ${isWrap:-f} = t ] ; then
    lastLineSz=$(( ${#str0} + 6 ))
  else
    lastLineSz=${#str0}
  fi

  formattedText=${str}
}

ln_hdf5()
{
  local link=$2

  # libs are made in check_targets
  mkdir -p local/include

  # $1=lib  could be mapped to lib64 by check_targets

  if ! check_targets hdf5 ${link_h} ; then
    return 1
  fi

  if ls ${link_h}/$lib/libhdf* &> /dev/null ; then
    ln -f -L -t local/$lib ${link_h}/$lib/libhdf* 2> /dev/null
  else
    log "no targets to link: ${link_h}/$lib/libhdf*" FAIL
    return 1
  fi

  if ls ${link_h}/include/H5* &> /dev/null ; then
    ln -f -L -t local/include ${link_h}/include/H5* 2> /dev/null
  else
    log "no targets to link: ${link_h}/include/H5*" FAIL
    return 1
  fi

  if ls ${link_h}/include/hdf5* &> /dev/null ; then
    ln -f -L -t local/include ${link_h}/include/hdf5* 2> /dev/null
  else
    log "no targets to link: ${link_h}/include/hdf5*" FAIL
    return 1
  fi

  if ls ${link_h}/bin/h5* &> /dev/null ; then
    mkdir  -p local/bin
    ln -f -L -t local/bin ${link_h}/bin/h5* 2> /dev/null
      # a failure is not essential
  fi

  if ls ${link_h}/bin/gif2h5* &> /dev/null ; then
    ln -f -L -t local/bin ${link_h}/bin/gif2h5* 2> /dev/null
  fi

  eval $1=$lib

  return 0
}

ln_netcdf()
{
  # libs are made in check_targets
  mkdir -p local/include

  # $1=lib  could be mapped to lib64 by check_targets

  if ! check_targets netcdf ${link_n} ; then
    return 1
  fi

  if ls ${link_n}/$lib/libnetcd* &> /dev/null ; then
    ln -f -L -t local/$lib ${link_n}/$lib/libnetcd* 2> /dev/null
  else
    log "no targets to link: ${link_n}/$lib/libnetcdf*" FAIL
    return 1
  fi

  if ls ${link_n}/include/netcdf* &> /dev/null ; then
    ln -f -L -t local/include ${link_n}/include/netcdf* 2> /dev/null
  else
    log "no targets to link: ${link_n}/include/netcdf*" FAIL
    return 1
  fi

  if ls ${link_n}/bin/nc* &> /dev/null ; then
    mkdir  -p local/bin
    ln -f -L -t local/bin ${link_n}/bin/nc* 2> /dev/null
    # a failure is not essential
  fi

  if ls ${link_n}/lib/pkgconfig/netcd* &> /dev/null ; then
    mkdir -p  local/$lib/pkgconfig
    ln -f -L -t local/lib/pkgconfig ${link_n}/lib/pkgconfig/netcd* 2> /dev/null
    # a failure is not essential
  fi

  eval $1=$lib

  return 0
}

ln_udunits()
{
  # libs are made in check_targets
  mkdir -p local/include

  # $1=lib  could be mapped to lib64 by check_targets

  if ! check_targets udunits ${link_u} ; then
    return 1
  fi

  if ls ${link_u}/$lib/libudunits2* &> /dev/null ; then
    ln -f -L -t local/$lib ${link_u}/$lib/libudunits2* 2> /dev/null
  else
    log "no targets to link: ${link_u}/$lib/libudunits2*" FAIL
    return 1
  fi

  if ls ${link_u}/include/udunits2.h &> /dev/null ; then
    ln -f -L -t local/include ${link_u}/include/udunits* 2> /dev/null
    ln -f -L -t local/include ${link_u}/include/converter.h 2> /dev/null
  else
    log "no targets to link: ${link_u}/include/netcdf*" FAIL
    return 1
  fi

  if ls ${link_u}/bin/udunits2 &> /dev/null ; then
    mkdir  -p local/bin
    ln -f -L -t local/bin ${link_u}/bin/udunits2 2> /dev/null
    # a failure is not essential
  fi

  if ls ${link_u}/lib/pkgconfig/udunits2* &> /dev/null ; then
    mkdir -p  local/$lib/pkgconfig
    ln -f -L -t local/lib/pkgconfig ${link_u}/lib/pkgconfig/udunits2* 2> /dev/null
    # a failure is not essential
  fi

  eval $1=$lib

  return 0
}

ln_zlib()
{
  # libs are made in check_targets
  mkdir -p local/include

  # $1=lib  could be mapped to lib64 by check_targets

  if ! check_targets zlib ${link_z} ; then
    return 1
  fi

  if [ -f ${link_z}/$lib/libz.a ] ; then
    ln -f -t local/$lib ${link_z}/$lib/libz.a 2> /dev/null
  else
    log "no targets to link: ${link_z}/$lib/libz.a" FAIL
    return 1
  fi

  if [ -f ${link_z}/include/zlib.h ] ; then
    ln -f -t local/include ${link_z}/include/zlib.h 2> /dev/null
  else
    log "no targets to link: ${link_z}/include/zlib.h" FAIL
    return 1
  fi

  if [ -f ${link_z}/include/zconf.h ] ; then
    ln -f -t local/include ${link_z}/include/zconf.h 2> /dev/null
  else
    log "no targets to link: ${link_z}/include/zconf.h" FAIL
    return 1
  fi

  if [ -f ${link_z}/$lib/pkgconfig/zlib.pc ] ; then
    mkdir -p  local/$lib/pkgconfig
    ln -f -t local/$lib/pkgconfig ${link_z}/$lib/pkgconfig/zlib.pc 2> /dev/null
    # a failure is not essential
  fi

  eval $1=$lib

  return 0
}

log()
{

  test ${isDebug:-f} = t && set +x

  # get status from last process
  local status=$?

  local n p
  local pEnd=80
  local str isDONE
  local term

  if [ ${isContLog:-f} = f ] ; then
    isContLog=t

    echo -e "\n$(date +'%F_%T'):" >> ${log_pwd}install.log
    isContLog=t
  fi

  n=$#
  local lastWord=${!n}
  if [ "${lastWord:0:4}" = DONE ] ; then
    term=${lastWord#*=}
    n=$(( n - 1 ))
    status=0
  elif [ "${lastWord}" = FAIL ] ; then
    term=FAIL
    n=$(( n - 1 ))
    status=1
  elif [ ${status} -eq 0 ] ; then
    term=DONE
  else
    term=FAIL
  fi

  for(( p=1 ; p <= n ; ++p )) ; do
    str="${str} ${!p}"
  done

  formatText "${str}"
  echo -e -n "$formattedText" >> ${log_pwd}install.log

  if [ ${#term} -gt 0 ] ; then
    str=' '
    for(( p=${lastLineSz} ; p < ${pEnd} ; ++p )) ; do
      str="${str}."
    done
    str="${str} ${term}"
  fi

  echo "$str" >> ${log_pwd}install.log

  test ${isDebug:-f} = t && set -x

  return $status
}

saveAsCycle()
{
  if [ "$1" = KEEP-ORIG ] ; then
    local isKeep=t
    shift 1
  fi

  for f in $* ; do
    if [ ! \( -f $f -o -d $f \) ] ; then
      echo "install.saveAsCycle: no such file or directory $f"
      return
    fi

    local ext val x
    local maxVal fs fx

    maxVal=0
    fs=( $(ls -d $f.* 2> /dev/null) )

    for fx in ${fs[*]} ; do
      ext=${fx##*.}

      if val=$(expr match $ext '\([[:digit:]]\+$\)' 2> /dev/null) ; then
        test ${val:-0} -gt ${maxVal} && maxVal=$val
      fi
    done

    if [ ${isKeep:-f} = t ] ; then
      cp -r $f ${f##*/}.$((++maxVal)) 2> /dev/null
    else
      mv $f ${f##*/}.$((++maxVal)) 2> /dev/null
    fi
  done
}

saveLocal()
{
  test -d $QA_PATH/local && \
    saveAsCycle $QA_PATH/local

  test -f $QA_PATH/install_configure && \
    saveAsCycle KEEP-ORIG $QA_PATH/install_configure

  return
}

tr_option()
{
  local phrase="${!1}"

  local sz i
  local sz=${#phrase}
  for((i=0 ; i < sz ; ++i )) ; do
    test "${phrase:i:1}" = '=' && break
  done

  if [ ${i} -eq ${sz} ] ; then
    phrase=$( echo "${phrase/% /}" | tr "[:lower:]" "[:upper:]" )
  else
    local tmp0="${phrase:0:i}"
    tmp0="${tmp0//QC/QA}"
    tmp0=$( echo "${tmp0/% /}" | tr "[:lower:]" "[:upper:]" )
    phrase="${tmp0}""${phrase:i}"
  fi

  eval ${1}=\${phrase}
  return
}

# ++++++++++++   main   +++++++++++++++

#QA_PATH was exported
qaLocalPath=${QA_PATH}/local

while getopts hq-: option ${args[*]}
do
  UOPTARG="$OPTARG"
  tr_option UOPTARG

  case $option in
    h)  descript
        exit 1 ;;
    q)  QUIET=t ;;
    -)  if [ "${UOPTARG%%=*}" = AUTOFIX ] ; then
           if [ "${UOPTARG#*=}" = DISABLE ] ; then
              sed -i '/autofix/ d' .conf &> /dev/null
              test ! -s .conf && \rm .conf
           else
              if ! grep -i -q autofix .conf &> /dev/null; then
                 echo autofix=enabled >> .conf
              fi
           fi
        elif [ "${UOPTARG:0:5}" = 'BUILD' ] ; then
          isBuild=t
        elif [ "${UOPTARG}" = CONTINUE_LOG ] ; then
           isContLog=t
        elif [ "${UOPTARG%=*}" = DEBUG ] ; then
           if [ "${UOPTARG}" = DEBUG -o ${OPTARG#*=} = ${0##*/} ] ; then
             set -x
             isDebug=t
           fi
        elif [ "${UOPTARG}" = DISTCLEAN ] ; then
           isDistClean=t
        elif [ "$UOPTARG" = HELP ] ; then
           descript
           exit 1
        elif [ "${UOPTARG:0:5}" = 'LINK=' ] ; then
           link_h=${OPTARG#*=}
           link_n=${OPTARG#*=}
           link_u=${OPTARG#*=}
           link_z=${OPTARG#*=}
           isLink=t
        elif [ "${UOPTARG:0:6}" = LINK_H ] ; then
           link_h=${OPTARG#*=}
           isLink=t
        elif [ "${UOPTARG:0:6}" = LINK_N ] ; then
           link_n=${OPTARG#*=}
           isLink=t
        elif [ "${UOPTARG:0:6}" = LINK_U ] ; then
           link_u=${OPTARG#*=}
           isLink=t
        elif [ "${UOPTARG:0:6}" = LINK_Z ] ; then
           link_z=${OPTARG#*=}
           isLink=t
        elif [ "${UOPTARG:0:5}" = LOCAL ] ; then
           qaLocalPath=${OPTARG#*=}
        elif [ "${UOPTARG%%=*}" = PACKAGE ] ; then
           package=${OPTARG#*=}
        elif [ "${OPTARG}" = saveLocal ] ; then
           saveLocal

        #undocumented; default from install overrides internal default
        elif [ "${UOPTARG%=*}" = HDF5 ] ; then
          curr_hdf5=${OPTARG#hdf5=}
        elif [ "${UOPTARG%=*}" = NETCDF ] ; then
          curr_netcdf=${OPTARG#netcdf=}
        elif [ "${UOPTARG%=*}" = ZLIB ] ; then
          curr_zlib=${OPTARG#zlib=}
        elif [ "${UOPTARG%=*}" = UDUNITS ] ; then
          curr_udunits=${OPTARG#udunits=}
        fi

        ;;
   \?)  descript
        exit 1
  esac
done

test ${isDebug:-f} = t && unset QUIET

shift $(( $OPTIND - 1 ))

log_pwd=$(pwd)/

# Installation of external packages.

mkdir -p $qaLocalPath

if ! mkdir -p $qaLocalPath/source 2> /dev/null ; then
  descript
  txt="Could not mkdir -p $qaLocalPath/source"
  echo -e "\n${txt}"

  log ${txt} DONE
  exit 1
fi

test ${isDistClean:-f} = t  && distclean

if [ ${isBuild:-f} = t ] ; then
  f_build
elif [ ${isLink:-f} = t ] ; then
  if [ "${link_z}" ] ; then
    test ! -d "${link_z}" && exit 1
  fi
  if [ "${link_h}" ] ; then
    test ! -d "${link_h}" && exit 1
  fi
  if [ "${link_n}" ] ; then
    test ! -d "${link_n}" && exit 1
  fi
  if [ "${link_u}" ] ; then
    test ! -d "${link_u}" && exit 1
  fi

  f_link
fi

exit 0
